// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpx1dEZHfQCMK7K7iHYLZ0Kb-UGE2F3qU',
    appId: '1:551293044493:web:ed62c67dae5074aa105244',
    messagingSenderId: '551293044493',
    projectId: 'ewallet-d78ce',
    authDomain: 'ewallet-d78ce.firebaseapp.com',
    storageBucket: 'ewallet-d78ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8cpxl9swXJDP9DaIRagPCH3Glwen0sqs',
    appId: '1:551293044493:android:441d32467e5166fc105244',
    messagingSenderId: '551293044493',
    projectId: 'ewallet-d78ce',
    storageBucket: 'ewallet-d78ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJEBaRy5e9RTz6UtE1bo8AYIF4v8KDt4',
    appId: '1:551293044493:ios:50df6f464b3a672a105244',
    messagingSenderId: '551293044493',
    projectId: 'ewallet-d78ce',
    storageBucket: 'ewallet-d78ce.appspot.com',
    iosClientId: '551293044493-bi1n380rhv15r658otff4ab6lgtic1hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJEBaRy5e9RTz6UtE1bo8AYIF4v8KDt4',
    appId: '1:551293044493:ios:50df6f464b3a672a105244',
    messagingSenderId: '551293044493',
    projectId: 'ewallet-d78ce',
    storageBucket: 'ewallet-d78ce.appspot.com',
    iosClientId: '551293044493-bi1n380rhv15r658otff4ab6lgtic1hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalproject',
  );
}
